from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
from dotenv import load_dotenv
import os
import certifi


load_dotenv()

USER: str | None = os.getenv('MONGODB_USER')
PASS: str | None = os.getenv('MONGODB_PASS')
CLUSTER: str | None = os.getenv('MONGODB_CLUSTER')

print(USER)
print(PASS)
print(CLUSTER)

# uri = f'mongodb+srv://{USER}:{PASS}@{CLUSTER}.kjfox.mongodb.net/?retryWrites=true&w=majority&appName={CLUSTER}'
uri = f"mongodb+srv://anachury:yQJRGDHBL3d34wKX@sebastianelmejorprofe.kjfox.mongodb.net/?retryWrites=true&w=majority&appName=SebastianElMejorProfe"


client = MongoClient(uri, server_api=ServerApi('1'), tlsCAFile=certifi.where())
db = client['estudiantes']
materias = db['materias']

materias.insert_many([
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Vojnov, Florencia', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '4'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Estrada, Felipe', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': 'N/A' } } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Ferrari, Pablo Nahuel', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': 'N/A'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Zelayeta, Julián', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': 'N/A'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Castelnovo, Lucas', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '6'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Hodes, Agustín', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': 'Ausente'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Schvartz, Guillermo', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '3'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Romero, Martín', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '4'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Cestari, Ariel', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '2'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Palumbo, Nahuel', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '9'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Pietrolati, Flavio', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '4'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Poschenrieder, Alexander', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '8'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Coro, Guillermo', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '7'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Fang, David', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '5'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Plá, Sebastian', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '8'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Toledo, Sebastian', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '7'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Casaubon, Javier', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': 'Ausente'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Branda, Nahuel', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '5'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Garcia, Diego', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': 'Ausente'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Clausi, Laureano', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '8'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'De los Santos, Martin Ariel', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '7'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Furman, Kevin', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '3'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'García, Cristian', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '9'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Grillo, Guillermo', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '7'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Montes de Oca, Francisco', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '5'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Morales, Matías', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '7'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Ramos, Andrea', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '2'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Bravo, Sebastian', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '5'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Franchino, Gonzalo', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '2'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Mallo, Emiliano', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '8'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Pantano, Fiamma', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '9'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'García, Franco', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '7'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Moll, Matias', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '9'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'García, Leandro Gabriel', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '7'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Sorella, Javier', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '9'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'La Ferraro, Matías', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '2'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Noya, Diego', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '6'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Vallone, Matías', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '4'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Gimbatti, Christian', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '6'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Grande, Leonardo', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '2'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Pardo, Nicolas', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '1'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3052', 'alumno': {'nombreApellido': 'Pinto, Ezequiel', 'parciales': [ { 'parcial': { 'fecha': '27/07/2013', 'nota': '4'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Eliaschev, Nicolás', 'parciales': [ { 'parcial': { 'fecha': '24/07/2013', 'nota': '8'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Pereyra, Ariel', 'parciales': [ { 'parcial': { 'fecha': '24/07/2013', 'nota': '4'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Saieg, Sebastian', 'parciales': [ { 'parcial': { 'fecha': '24/07/2013', 'nota': '10'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Valente, Miguel', 'parciales': [ { 'parcial': { 'fecha': '24/07/2013', 'nota': '7'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Delpino, Ruben', 'parciales': [ { 'parcial': { 'fecha': '24/07/2013', 'nota': '2'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Fermepin, Andres', 'parciales': [ { 'parcial': { 'fecha': '24/07/2013', 'nota': '9'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Rocchio, Claudio', 'parciales': [ { 'parcial': { 'fecha': '24/07/2013', 'nota': '2'} }, { 'parcial': { 'fecha': '29/08/2013', 'nota': '9'} } ] } },
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Rosado, Federico', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '6'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Gómez, María', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '7'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Salazar, Julieta', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '9'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Martínez, Javier', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '8'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Cabrera, Mateo', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '5'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Fernández, Sofía', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '9'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Sánchez, Camila', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '10'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'González, Tomás', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '4'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Pérez, Lucía', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '8'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Vargas, Nicolás', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '7'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Ramos, Adrián', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '6'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Ortiz, Valentina', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '9'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Moreno, Alejandro', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '5'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Rodríguez, Ana', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '7'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Navarro, Diego', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '6'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'López, Victoria', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '10'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Ruiz, Leonardo', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '8'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'García, Rodrigo', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '7'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Molina, Sandra', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '6'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3053', 'alumno': {'nombreApellido': 'Rojas, Juan', 'parciales': [{'parcial': {'fecha': '24/07/2013', 'nota': '9'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Alonso, Carla', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '5'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Medina, Gabriela', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '6'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Figueroa, Esteban', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '4'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Paz, Florencia', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '7'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Aguilar, Paula', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '8'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Herrera, Facundo', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '9'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Núñez, Sergio', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '5'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Lara, Joaquín', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '7'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Maldonado, Elena', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '6'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Silva, Gonzalo', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '9'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Montoya, Beatriz', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '7'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Ibarra, Oscar', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '8'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Castro, Nicolás', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '10'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Vega, Patricia', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '9'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Cáceres, Agustina', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '5'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Campos, Alejandro', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '7'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Chávez, Emilia', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '6'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Benítez, Martín', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '9'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Reyes, Daniela', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '8'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Arias, Pablo', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '6'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Méndez, Carla', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '7'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3054', 'alumno': {'nombreApellido': 'Bravo, Jorge', 'parciales': [{'parcial': {'fecha': '23/07/2013', 'nota': '8'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Valdez, Lucas', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '10'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Varela, Carmen', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '6'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Palacios, Gonzalo', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '8'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Rivero, Gabriela', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '7'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Roldán, Andrés', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '9'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Ayala, Agustín', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '7'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Bustos, Laura', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '8'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Espinoza, Francisco', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '6'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Soria, Fernando', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '7'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Peralta, Dolores', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '5'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Gutiérrez, Julián', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '10'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Cruz, Mariano', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '8'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Peña, Eduardo', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '6'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Soto, Alejandra', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '7'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Ponce, Lorena', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '8'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Ríos, Esteban', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '5'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Carrasco, Matías', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '9'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Nieves, Carla', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '10'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Torres, Ignacio', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '8'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Mora, Elena', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '6'}}]}},
    {'materia': 'Diseño de Sistemas', 'curso': 'K3055', 'alumno': {'nombreApellido': 'Sáez, Guillermo', 'parciales': [{'parcial': {'fecha': '25/07/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2021', 'alumno': {'nombreApellido': 'García, Ana', 'parciales': [{'parcial': {'fecha': '15/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2021', 'alumno': {'nombreApellido': 'López, Juan', 'parciales': [{'parcial': {'fecha': '15/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2021', 'alumno': {'nombreApellido': 'Martínez, Lucía', 'parciales': [{'parcial': {'fecha': '15/08/2013', 'nota': '9'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2021', 'alumno': {'nombreApellido': 'Rodríguez, Carlos', 'parciales': [{'parcial': {'fecha': '15/08/2013', 'nota': '6'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2021', 'alumno': {'nombreApellido': 'Pérez, Mariana', 'parciales': [{'parcial': {'fecha': '15/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2022', 'alumno': {'nombreApellido': 'Gómez, Laura', 'parciales': [{'parcial': {'fecha': '17/08/2013', 'nota': '10'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2022', 'alumno': {'nombreApellido': 'Ruiz, Diego', 'parciales': [{'parcial': {'fecha': '17/08/2013', 'nota': '5'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2022', 'alumno': {'nombreApellido': 'Fernández, Sofía', 'parciales': [{'parcial': {'fecha': '17/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2022', 'alumno': {'nombreApellido': 'Sánchez, Pedro', 'parciales': [{'parcial': {'fecha': '17/08/2013', 'nota': '9'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2022', 'alumno': {'nombreApellido': 'Torres, Clara', 'parciales': [{'parcial': {'fecha': '17/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2023', 'alumno': {'nombreApellido': 'Ramírez, Luis', 'parciales': [{'parcial': {'fecha': '19/08/2013', 'nota': '6'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2023', 'alumno': {'nombreApellido': 'Vega, Isabel', 'parciales': [{'parcial': {'fecha': '19/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2023', 'alumno': {'nombreApellido': 'Flores, Javier', 'parciales': [{'parcial': {'fecha': '19/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2023', 'alumno': {'nombreApellido': 'Morales, Julia', 'parciales': [{'parcial': {'fecha': '19/08/2013', 'nota': '9'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2023', 'alumno': {'nombreApellido': 'Castro, Pablo', 'parciales': [{'parcial': {'fecha': '19/08/2013', 'nota': '5'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2023', 'alumno': {'nombreApellido': 'Ortiz, Mónica', 'parciales': [{'parcial': {'fecha': '19/08/2013', 'nota': '10'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Silva, Alberto', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Moreno, Natalia', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '6'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Aguilar, Fernando', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '9'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Mendoza, Elena', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Vargas, Mateo', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Reyes, Daniel', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Campos, Andrea', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '9'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Núñez, Sergio', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Iglesias, Marta', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '6'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Mora, Javier', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '9'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Soto, Julia', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '5'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Durán, Manuel', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Ríos, Lorena', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Vera, Pedro', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '10'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Cruz, Marta', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '6'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Guerrero, Sofia', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '9'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Herrera, Luis', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Peña, Maria', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2024', 'alumno': {'nombreApellido': 'Vargas, Elena', 'parciales': [{'parcial': {'fecha': '21/08/2013', 'nota': '10'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Blanco, Pablo', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '5'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Ramos, Angela', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Escobar, Alberto', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Romero, Camila', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '9'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Gutiérrez, Carlos', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '6'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Muñoz, Sara', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Méndez, Jorge', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Flores, Daniela', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '9'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Navarro, Hugo', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '5'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Reyes, Paula', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Pérez, Mario', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Ortiz, Valeria', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '9'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Vargas, Santiago', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '6'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Molina, Alicia', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Moreno, Francisco', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Sosa, Laura', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '9'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2025', 'alumno': {'nombreApellido': 'Santos, David', 'parciales': [{'parcial': {'fecha': '23/08/2013', 'nota': '10'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Herrera, Paula', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Cabrera, Jorge', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Gómez, Alicia', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '6'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'López, Carlos', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '9'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Román, Sara', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Castro, Juan', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '5'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'García, Sofia', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '10'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Martínez, Javier', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Sánchez, Laura', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '6'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Álvarez, Sergio', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '9'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Ruiz, Elena', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Paredes, David', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '5'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Hernández, Maria', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Jiménez, Ana', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Rey, Hugo', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '9'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Navas, Marta', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '6'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Salas, Luis', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '8'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Torres, Elena', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '7'}}]}},
    {'materia': 'Redes de Computadoras', 'curso': 'R2026', 'alumno': {'nombreApellido': 'Gil, Andres', 'parciales': [{'parcial': {'fecha': '25/08/2013', 'nota': '9'}}]}}
])
